<?php 
	define('VERSION', '1.4 beta');
	define('SITE', '/');
	define('DR', $_SERVER['DOCUMENT_ROOT'].'/');
	define('ADMIN', DR.'admin/');
	define('FILES', 'files/');
	define('REORDERED', '<div class="alert alert-success"><strong>Success!</strong> Порядок сохранен!</div>');
	define('ARTICLES', 'Список статьи');
	define('DEFAULT_CATEGORY', '1');
	define('ID', 'ID');
	define('TITLE', 'Название');
	define('CATEGORY', 'Категория');
	define('RUSSIAN', 'Русский');
	define('ENGLISH', 'Английский');
	define('STATUS', 'Статус');
	define('NO_TRANSLATION', '<span class="red">Нет перевода</span>');
	define('ARTICLE', 'Статья');
	define('CREATE', 'Создать');
	define('DELETE', 'Удалить');
	define('RESTORE', 'Восстановить');
	define('VIEW_LIST', 'Список');
	define('TRASH', 'Корзина');
	define('SEARCH', 'Поиск');
	define('FIND', 'Искать');
	define('NEW_ARTICLE', 'Новая статья');
	define('SAVE', 'Сохранить');
	define('SAVE_AND_NEW', 'Сохранить и создать');
	define('SAVE_AND_CLOSE', 'Сохранить и закрыть');
	define('CLOSE', 'Закрыть без сохранений');
	define('INTRO', 'Интро');
	define('FULL_TEXT', 'Полный текст');
	define('EDIT_ARTICLE', 'Редактировать статью');
	define('CATEGORIES', 'Список категорий');
	define('PARENT_CATEGORY', 'Родительская категория');
	define('ROOT_OPTION', '<option value="1">Корневая</option>');
	define('ROOT_OPTION_SELECTED', '<option value="1" selected>Корневая</option>');
	define('NEW_CATEGORY', 'Новая категория');
	define('EDIT_CATEGORY', 'Редактировать категорию');
	define('NOT_SAVED', '<div class="alert alert-danger"><strong>Error!</strong> Не удалось сохранить!</div>');
	define('DOCUMENTS', 'Документы');
	define('DOCUMENT_LINK', 'Ссылка на документ');
	define('DOCUMENTS_FOLDER', 'Папки документов');
	define('UPLOAD_DOCUMENTS', 'Загружать документы');
	define('MAX_UPLOAD_DOCUMENT_SIZE', '10485760');
	define('UPLOAD', 'Загрузить');
	define('DB_HOST', 'localhost');
	define('DB_USER', '');
	define('DB_PASS', '');
	define('DB_NAME', '');
	define('LOGIN', 'Логин');
	define('PASS', 'Пароль');
	define('SIGN_IN', 'Войти');
	define('MENUS', 'Меню');
	define('MODULES', 'Модули');
	define('GALLERIES', 'Галерея');
	define('IMAGES', 'Изображения');
	define('NEW_GALLERY', 'Новая галерея');
	define('UPLOAD_GALLERY', 'Загружать рисунки');
	define('MAX_UPLOAD_IMAGE_SIZE', '1048576');
	define('COMPONENTS', 'Компоненты');
?>
